apiVersion: apps/v1
kind: Deployment
metadata:
  name: dssp
  namespace: namespace1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dssp
  template:
    metadata:
      labels:
        app: dssp
    spec:
      containers:
      - name: dssp
        image: <initial-image>  # Specify a placeholder or the initial image
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: namespace1
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: dssp
