name: '2. Build and Deploy Web App'

on: 
  workflow_dispatch:
  push:
    paths:
      - 'App1/docker-nodejs-sample/**'
      
jobs:
    build-and-deploy:
      runs-on: ubuntu-latest
      environment: Development
      steps:
      - name: "checkout"
        uses: actions/checkout@main
        
   #   - name: 'Login to Azure'
    #    env:
     #      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      #  run: |
       #   echo $AZURE_CREDENTIALS | az login --service-principal -u $CLIENT_ID -p $CLIENT_SECRET --tenant $TENANT_ID

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        env:
           AZURE_CLIENT_ID: ${{ secrets.CLIENT_ID }}
           AZURE_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
           AZURE_TENANT_ID: ${{ secrets.TENANT_ID }}
           AZURE_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
              
      - name: 'Build and push image'
        uses: azure/docker-login@v1
        with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          cp -r ./App/sample-web-app/* .
          docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/dssp:${{ github.sha}}
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/dssp:${{ github.sha }}
      
      - name: Set up kubectl
        run: |
            az aks get-credentials --resource-group ${{ secrets.RESOURCE_GROUP }} --name infrarg1

      - name: Create Namespace
        run: |
            kubectl create namespace namespace || echo "Namespace already exists"

      - name: Deploy to AKS
        run: |
            kubectl apply -f deployment.yaml -n namespace
            kubectl set image deployment/dssp dssp=${{ secrets.REGISTRY_LOGIN_SERVER }}/dssp:${{ github.sha }} -n namespace
            kubectl rollout status deployment/dssp -n namespace
      
