name: '2. Build and Deploy Web App'

on: 
  workflow_dispatch:
  push:
    paths:
      - 'App/sample-web-app/**'
      
jobs:
    build-and-deploy:
      runs-on: ubuntu-latest
      environment: Development
      steps:
      - name: "checkout"
        uses: actions/checkout@main

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
      
