name: 'create infra'

on:
   workflow_dispatch: 
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
         shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Terrafrom
      uses: hashicorp/setup-terraform@v1
     # with: 
      #  cli_config_credentials_token: ${{ secrets.CLIENT_SECRET }}
    - name: Set Azure Credentials
      run: |
          echo "Setting up Azure credentials for Terraform..."
          echo "ARM_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}" >> $GITHUB_ENV
          echo "ARM_CLIENT_SECRET=${{ secrets.AZURE_CLIENT_SECRET }}" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}" >> $GITHUB_ENV
          echo "ARM_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
    - name: Terrafrom Init
      run: |
        cp ./Infra/* .
         terraform init
    - name: Terrafrom Plan
      run: |
        cp ./Infra/* .
        terraform plan -input=false
    - name: Terrafrom Apply
      run: |
        cp ./Infra/* .
        terraform apply -auto-approve -input=false

 
